### ISSUE TITLE
Graphs don't show up on Safari iOS 14

### ISSUE THREAD

**Issue by VotusX** [mauriciopoppe/function-plot#301] opened 2024-06-04 19:19 UTC
Hey there,

I just wanted to draw attention to an issue I discovered. Using the latest version, I tried to display a graph inside of a WKWebView inside an iOS app I'm developing. On one of my testing devices (iPad Air 4th generation, iOS 14.2) the graphs aren't showing up, while they do on my other device (iPhone 14 Pro, iOS 16.0.2).

Trying to get to the bottom of this, I went to the project's [website](https://mauriciopoppe.github.io/function-plot/) on that iPad and neither of the examples were visible. I connected to the javascript console via Safari on mac and got the errors visible in the first screenshot. In the second one, you can see what was visible instead of the sandbox.

Just wanted to let you know!

Best regards

<img width="1003" alt="console-errors" src="https://github.com/mauriciopoppe/function-plot/assets/77923909/9be4e83f-2312-4f0e-9de0-1e7857f3fb6b">

![website-errors](https://github.com/mauriciopoppe/function-plot/assets/77923909/eaf253ab-b376-4f7d-8e20-b202ace6a353)

**Comment by mauriciopoppe** [comment] 2024-06-05 02:56
Thanks for the report, I'm also seeing similar issues with Safari in iOS 17.

I see that the graph renders but attempting to zoom causes it to throw a runtime error
<img width="348" alt="image" src="https://github.com/mauriciopoppe/function-plot/assets/1616682/b297d374-b5ab-4e35-a8bd-29307aed1e01">

```
TypeError: The provided value is non-finite
```

I tracked it to the [d3-selection](https://github.com/d3/d3-selection/blob/d8ea8005f87ca72496d748a91ab6e0ccbe1a2011/src/pointer.js#L10) selection package attempting to assign `undefined` to the coordinates of an SVG Point

https://github.com/d3/d3-selection/blob/d8ea8005f87ca72496d748a91ab6e0ccbe1a2011/src/pointer.js#L10

![image](https://github.com/mauriciopoppe/function-plot/assets/1616682/d62de02d-e5e1-4cff-8b1b-944663fb5eec)

I'm using the latest version of the d3-selection package. I saw that unfortunately this error was being thrown for a long time but because when you zoom there are many runs of the draw method, a few of the runs will be broken with the error above but it's just going to break that run.

**Comment by mauriciopoppe** [comment] 2024-06-05 03:00
About the error you see I see in https://caniuse.com/mdn-javascript_builtins_object_hasown that there's support for `Object.hasOwn` in these versions:

<img width="84" alt="image" src="https://github.com/mauriciopoppe/function-plot/assets/1616682/692f9616-697c-45e7-8e7c-7a9ac614a973">

I see in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn#browser_compatibility that it was released in Safari 15.4, I'd suggest either polyfilling the app you have so that `Object.hasOwn` exists or to use a newer Safari version.

**Comment by VotusX** [comment] 2024-06-05 17:12
Thanks for your suggestions! I will try and see. Are you planning to fix this issue in a future release?

**Comment by mauriciopoppe** [comment] 2024-06-07 04:20
For the error: `"TypeError: The provided value is non-finite"`, given that the issue is present in the d3-selection library and how it behaves on zoom in Safari I could only fix it if I patch it during build e.g. override the `node_modules/d3-selection/src/pointer.js#L10` code.

For the `Object.hasOwn` I don't think I'll add the polyfill in the project given that's now natively supported in all the browsers, instead apps that use the library should polyfill it if the browser they target doesn't support this natively.

**Closed** 2024-11-02 16:50 UTC
Labels: wontfix
