### ISSUE TITLE
Problem plotting "pow()"

### ISSUE THREAD

**Issue by jlfernandez83** [mauriciopoppe/function-plot#110] opened 2017-12-06 08:46 UTC
Hi again. When you use the pow() function with x in exponent, it doesn't draw anything, although the tip moves through the invisible graph:

`window.d3 = require('d3');`
`var functionPlot = require('function-plot');`

`opts = {`
`  target: '#expyap_container_2276',`
 
`  grid: false,`
`  data: [{`
`    fn: 'pow(2,x)'`
`  }]`
`};`

`instance = functionPlot(opts);`

**Comment by juanchireca** [comment] 2017-12-13 20:43
yes @jlfernandez83 , i have the same problem.

Also implicit functions and exponencial like `x^y` are not working. In this case, does not appear the tip.

Anyways, the library is awesome

**Comment by ELC** [comment] 2019-11-17 12:12
I had the same problem, but using `'graphType': 'scatter'` solved the issue

**Comment by mauriciopoppe** [comment] 2020-06-12 21:29
closing as a duplicate of #143

**Closed by mauriciopoppe** 2020-06-12 21:29 UTC
