### ISSUE TITLE
Failed to parse source map when building with create-react-app

### ISSUE THREAD

**Issue by NoahK216** [mauriciopoppe/function-plot#304] opened 2024-06-12 22:15 UTC
It will finish the build and I can view it locally, but when deploying it to my Heroku dyno I recieve an application error when opening any page.

Here are the warnings from the build process:
Failed to parse source map from 'E:\...\node_modules\interval-arithmetic\src\operations\utils.ts' file: Error: ENOENT: no such file or directory, open 'E:\...\node_modules\interval-arithmetic\src\operations\utils.ts'

Failed to parse source map from 'E:\...\node_modules\interval-arithmetic\src\round.ts' file: Error: ENOENT: no such file or directory, open 'E:\...\node_modules\interval-arithmetic\src\round.ts'

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in ./node_modules/function-plot/dist/chart.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'E:\...\node_modules\function-plot\src\chart.ts' file: Error: ENOENT: no such file or directory, open 'E:\...\node_modules\function-plot\src\chart.ts'

WARNING in ./node_modules/function-plot/dist/datum-defaults.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'E:\...\node_modules\function-plot\src\datum-defaults.ts' file: Error: ENOENT: no such file or directory, open 'E:\...\node_modules\function-plot\src\datum-defaults.ts'

**Comment by mauriciopoppe** [comment] 2024-06-19 19:57
This looks like a bundler specific problem, if there's an issue please submit a minimal reproducible example.

**Comment by mauriciopoppe** [comment] 2024-11-02 16:49
Marking as closed, feel free to reopen with a minimal reproducible example.

**Closed by mauriciopoppe** 2024-11-02 16:49 UTC
